version: '3.8'

services:
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.0
    environment:
      - discovery.type=single-node
    ports:
      - 19200:9200
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data

  app:
    build: app/
    ports:
      - 5080:80
    depends_on:
      - mongodb
      - elasticsearch
    environment:
      - ConnectionStrings__MongoDB=mongodb://mongodb:27017
      - ConnectionStrings__Elasticsearch=http://elasticsearch:9200
  
  nginx:
    image: nginx
    ports:
      - 5000:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

volumes:
  mongodb_data: {}
  elasticsearch_data: {}
