version: '3.8'

services:
  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.0
    restart: always
    environment:
      - discovery.type=single-node
    ports:
      - 19200:9200
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 5080:80
    depends_on:
      - mongodb
      - elasticsearch
    environment:
      - ConnectionStrings__MongoDB=mongodb://mongodb:27017
      - ConnectionStrings__Elasticsearch=http://elasticsearch:9200

volumes:
  mongodb_data: {}
  elasticsearch_data: {}
